//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitHistories
    {
        public int Id { get; set; }
        public string Complaints { get; set; }
        public System.DateTime VisitDate { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
        public int DiagnosisId { get; set; }
    
        public virtual Diagnoses Diagnoses { get; set; }
        public virtual Doctors Doctors { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
